#!/usr/bin/env python3
"""
log_to_kml.py — Convert a GhostMesh node log CSV to KML for Google Earth / QGIS.

Expected CSV format (generated by GhostMesh Phase 4 logging):
    timestamp,node_id,message,lat,lon,rssi,snr

Usage:
    python log_to_kml.py input.csv output.kml
    python log_to_kml.py input.csv              # writes input.kml

Rows without lat/lon are included as placemarks at 0,0 with a note.
Rows with lat/lon are plotted at their reported position.
"""

import csv
import sys
import os
from datetime import datetime
from xml.sax.saxutils import escape


KML_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
  <name>{name}</name>
  <description>GhostMesh node log export — {count} entries</description>
  <Style id="node-style">
    <IconStyle>
      <color>ff00aaff</color>
      <scale>1.0</scale>
      <Icon><href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href></Icon>
    </IconStyle>
    <LabelStyle><scale>0.8</scale></LabelStyle>
  </Style>
"""

KML_PLACEMARK = """  <Placemark>
    <name>{node_id}</name>
    <description><![CDATA[
      <b>Time:</b> {timestamp}<br/>
      <b>Node:</b> {node_id}<br/>
      <b>Message:</b> {message}<br/>
      <b>RSSI:</b> {rssi} dBm<br/>
      <b>SNR:</b> {snr} dB
    ]]></description>
    <styleUrl>#node-style</styleUrl>
    <Point><coordinates>{lon},{lat},0</coordinates></Point>
  </Placemark>
"""

KML_FOOTER = """</Document>
</kml>
"""

REQUIRED_FIELDS = {"timestamp", "node_id", "message"}
OPTIONAL_FIELDS = {"lat", "lon", "rssi", "snr"}


def parse_float(value, default=0.0):
    try:
        return float(value)
    except (ValueError, TypeError):
        return default


def convert(input_path: str, output_path: str) -> int:
    placemarks = []

    with open(input_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            print("ERROR: CSV has no header row.", file=sys.stderr)
            return 1

        missing = REQUIRED_FIELDS - set(reader.fieldnames)
        if missing:
            print(f"ERROR: CSV is missing required columns: {missing}", file=sys.stderr)
            return 1

        for i, row in enumerate(reader, start=2):
            lat = parse_float(row.get("lat", ""), 0.0)
            lon = parse_float(row.get("lon", ""), 0.0)
            rssi = row.get("rssi", "N/A")
            snr = row.get("snr", "N/A")

            placemarks.append(KML_PLACEMARK.format(
                node_id=escape(row.get("node_id", f"node_{i}")),
                timestamp=escape(row.get("timestamp", "")),
                message=escape(row.get("message", "")),
                lat=lat,
                lon=lon,
                rssi=rssi,
                snr=snr,
            ))

    doc_name = escape(os.path.basename(input_path))
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(KML_HEADER.format(name=doc_name, count=len(placemarks)))
        f.writelines(placemarks)
        f.write(KML_FOOTER)

    print(f"Wrote {len(placemarks)} placemarks to {output_path}")
    return 0


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    input_path = sys.argv[1]
    if len(sys.argv) >= 3:
        output_path = sys.argv[2]
    else:
        base = os.path.splitext(input_path)[0]
        output_path = base + ".kml"

    if not os.path.isfile(input_path):
        print(f"ERROR: Input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    sys.exit(convert(input_path, output_path))


if __name__ == "__main__":
    main()
